version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
      tag: '12.3'
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run test
